<?php 

	$titles = array(
		'Sit Amet Consectetuer Adipiscing Elit Aliquam',
		'Sodales Purus In Molestie',
		'Quis Pede Suspendisse Dui',
		'Tristique Neque Venenatis Lacus Etiam',
		'Egestas Sed Pharetra Felis Eget Varius',
		// 'Morbi Metus Vivamus Euismod',
		// 'Suspendisse Ac Metus Vitae Velit',
		// 'Elementum Purus Accumsan Interdum',
		// 'Natoque Penatibus Et Magnis Dis',
		// 'Semper Rutrum Fusce Dolor Quam',
		// 'Tempor Erat Neque Non Quam Pellentesque',
		// 'Scelerisque Lorem Ipsum Sodales Purus In',
		// 'Morbi Tristique Senectus Et Netus Et',
		// 'Nec Euismod In',
		// 'Orci Sem Eget',
		// 'Mauris Ut Mi Duis Risus Odio',
		// 'Lorem Ac Risus Morbi',
		// 'Tincidunt Donec Vitae Erat',
		// 'Amet Risus Donec Egestas',
		// 'Vitae Odio Sagittis Semper',
		// 'Suspendisse Ac Metus Vitae Velit Egestas',
		// 'Quis Massa Mauris Vestibulum',
		// 'Erat Nonummy Ultricies Ornare',
		// 'Quis Turpis Vitae Purus',
		// 'Suspendisse Dui Fusce Diam',
		// 'Proin Velit Sed',
		// 'Pellentesque Habitant Morbi Tristique Senectus Et',
		// 'Ac Nulla In Tincidunt Congue Turpis',
		// 'Risus Nulla Eget',
		// 'Vitae Purus Gravida Sagittis Duis',
		// 'Tortor Nunc Commodo Auctor',
		// 'Sagittis Augue Eu',
		// 'Elit Pretium Et',
		// 'Nullam Velit Dui Semper Et',
		// 'A Arcu Sed Et Libero',
		// 'Quis Lectus Nullam Suscipit',
		// 'Nunc Ullamcorper Eu Euismod Ac',
		// 'Lorem Semper Auctor',
		// 'Ut Nulla Cras Eu Tellus Eu',
		// 'Facilisi Sed Neque Sed',
		// 'Dapibus Rutrum Justo Praesent',
		// 'Turpis Aliquam Adipiscing Lobortis Risus',
		// 'Ut Sagittis Lobortis Mauris Suspendisse',
		// 'Orci Luctus Et Ultrices Posuere Cubilia',
		// 'Eget Tincidunt Dui Augue Eu',
		// 'Dui Fusce Diam Nunc Ullamcorper Eu',
		// 'Sollicitudin A Malesuada Id',
		// 'Ultricies Dignissim Lacus Aliquam Rutrum Lorem',
		// 'Vivamus Nisi Mauris Nulla Integer',
		// 'Ut Quam Vel Sapien Imperdiet',
	);

?>